COM THIS IS MY OWN BORG PROGRAM
COM IT IS LESS COOL BECAUSE IT DOES NOT HAVE LORD OF THE RINGS REFERENCES IN IT
START
	VAR MICKEY = 24
	PRINT MICKEY
	PRINT MICKEY % 2
	START
		MICKEY = 991
		START
			VAR JOEY = 11
			PRINT JOEY
		FINISH
		PRINT JOEY
		MICKEY ++
		PRINT MICKEY
	FINISH
	MICKEY --
	MICKEY --
	PRINT MICKEY
	PRINT JOEY
	VAR LEE = MICKEY ^ 2
	PRINT LEE
	COM LEE IS MICKEY TO THE MICKEY-TH POWER
FINISH